blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/TCz3t9k
    about: Get direct support and hang out with us
  - name: Wiki
    url: https://wiki.xboxdev.store/
    about: For assistance with setting up the Emulator
